version: '3'
services:
  cash-manager:
    build:
      context: .
    ports:
      - "8080:8080"
    networks:
      - cash-manager
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    restart: always
    volumes:
        - ./mysql-dump:/docker-entrypoint-initdb.d
    networks:
      - cash-manager
    environment:
      - MYSQL_ROOT_PASSWORD=cashmanager
      - MYSQL_DATABASE=cash_manager

networks:
  cash-manager: