version: '3'
services:
  cash_manager:
    container_name: cash_manager
    image: yabbes/cash-manager:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - "mysqldb"
    environment:
       SPRING_DATASOURCE_URL: $SPRING_DATASOURCE_URL
       SPRING_DATASOURCE_USERNAME: $SPRING_DATASOURCE_USERNAME
       SPRING_DATASOURCE_PASSWORD: $SPRING_DATASOURCE_PASSWORD
    expose:
      - "8080"
    working_dir: /app
    command: mvn clean spring-boot:run

  mysqldb:
    container_name: mysqldb
    image: mysql:8
    restart: always
    security_opt:
      - seccomp:unconfined
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
