version: '3'
services:
  cash_manager:
    container_name: cash_manager
    image: yabbes/cash-manager:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - "mysqldb"
    working_dir: /app
    command: bash -c "mvn -f ./pom.xml clean package install && java -jar ./target/cash-manager-43.jar"

  mysqldb:
    container_name: mysqldb
    image: mysql:8
    restart: always
    security_opt:
      - seccomp:unconfined
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
