version: '2.1'
services:
  cash_manager:
    container_name: cash_manager
    image: yabbes/cash-manager:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      mysqldb:
        condition: "service_healthy"
    working_dir: /app

  mysqldb:
    container_name: mysqldb
    image: mysql:8
    restart: always
    security_opt:
      - seccomp:unconfined
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=cashmanager
      - MYSQL_DATABASE=cash_manager
    volumes:
      - ./mysql:/etc/mysql/conf.d
      - ./mysql-dump:/docker-entrypoint-initdb.d
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=cashmanager --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 20