-- MySQL Script generated by MySQL Workbench
-- Mon Oct 14 16:50:20 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cash_manager
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cash_manager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cash_manager` DEFAULT CHARACTER SET utf8 ;
USE `cash_manager` ;

-- -----------------------------------------------------
-- Table `cash_manager`.`Panier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cash_manager`.`panier` (
  `id_panier` INT AUTO_INCREMENT,
  `id_produit` INT,
  `id_client` INT,
  PRIMARY KEY (`id_panier`))

ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `cash_manager`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cash_manager`.`client` (
  `id_client` INT AUTO_INCREMENT,
  `nom` TEXT,
  `prenom` TEXT,
  PRIMARY KEY (`id_client`))

ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `cash_manager`.`Produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cash_manager`.`produit` (
  `id_produit` INT AUTO_INCREMENT,
  `Name` TEXT,
  `image` BLOB,
  `prix` DOUBLE,
  PRIMARY KEY (`id_produit`))

ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cash_manager`.`ModePaiement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cash_manager`.`mode_paiement` (
  `id_mode_paiement` INT AUTO_INCREMENT,
  `mode_paiement` TEXT,
  PRIMARY KEY (`id_mode_paiement`))

ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cash_manager`.`Paiement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cash_manager`.`paiement` (
  `id_paiement` INT AUTO_INCREMENT,
  `id_client` INT,
  `id_mode_paiement` INT,
  `id_panier` INT,
  PRIMARY KEY (`id_paiement`))

ENGINE = InnoDB;

ALTER TABLE `cash_manager`.`paiement`
  ADD CONSTRAINT `paiment_FK_MDPAIE`
    FOREIGN KEY (`id_paiement`)
    REFERENCES `cash_manager`.`mode_paiement` (`id_mode_paiement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  ADD CONSTRAINT `paiment_FK_PANIER`
    FOREIGN KEY (`id_paiement`)
    REFERENCES `cash_manager`.`panier` (`id_panier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;


ALTER TABLE `cash_manager`.`panier`
    ADD CONSTRAINT `panier_FK_PRODUIT`
    FOREIGN KEY (`id_panier`)
    REFERENCES `cash_manager`.`produit` (`id_produit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  ADD CONSTRAINT `panier_FK_CLIENT`
    FOREIGN KEY (`id_panier`)
    REFERENCES `cash_manager`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

INSERT INTO `cash_manager`.`produit` (Name, Prix) VALUES ("Pain", 1);
INSERT INTO `cash_manager`.`produit` (Name, Prix) VALUES ("Kebab", 5);
INSERT INTO `cash_manager`.`client` (nom, prenom) VALUES ("John", "Doe");
INSERT INTO `cash_manager`.`client` (nom, prenom) VALUES ("Morgan", "Freeman");


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
