-- MySQL Script generated by MySQL Workbench
-- Mon Oct 14 16:50:20 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema cash_manager
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cash_manager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cash_manager` DEFAULT CHARACTER SET utf8 ;
USE `cash_manager` ;


